config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'recruits', to: 'recruit#index'
  get 'recruits/:id', to: 'recruit#show'
  get 'characters', to: 'character#show'
  post 'characters', to: 'character#create'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates_presence_of :email, :picture, :first_name, :last_name

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

end

app/controllers/character_controller.rb
class CharacterController < ApplicationController

  def show
    @candidate = CharacterService.new.get_character_data
    session[:current_candidate] = @candidate
  end

  def create
    new_character = Character.create(create_character)
    if new_character.save!
      flash[:success] = "#{new_character.last_name} has been recruited! Certify #{new_character.last_name} with a badge to make it offical!"
      redirect_to :root
    end
  end

  private

    def create_character
      {
        email: create_email + "@example.com",
        picture: session[:current_candidate]['picture'],
        first_name: "Recruit",
        last_name: session[:current_candidate]['name']
      }
    end

    def create_email
      a = session[:current_candidate]['name'].split('')
      b = []
      a.each do |s|
        if s == " "
          s = "_"
        end
        b << s
      end
      b.join
    end

end

app/controllers/recruit_controller.rb
class RecruitController < ApplicationController

  def index
    @recruits = Character.all
  end

  def show
    @recruit = Character.find(params[:id])
    recruit_service = BadgeService.new.post_badge_cred(@recruit.first_name, @recruit.last_name, @recruit.email)
    @recruit.update(certified: :true)
    flash[:success] = "#{@recruit.last_name} Certified!"
    redirect_to '/recruits'
  end

end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/character/show.html.erb
<%= link_to 'HOME', '/' %>
<h1>Character Show Page</h1>

<h3>Character: <%= @candidate.name %><br></h3>
<h3>Number of Comics: <%= @candidate.comics %><br></h3>

<%= image_tag(@candidate.picture) %>

<%= button_to 'Recruit Candidate', characters_path %>
<%= link_to 'Find New Candidate', '/characters' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Credly Take-home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag "application" %>
    <%= stylesheet_pack_tag "application" %>
  </head>

  <body>
<style media="screen">
  body {
    background-color: #DCDCDC;
  }

</style>
    <div id="flashMessage">
      <% flash.each do |type, message| %>
        <h1><%= message %></h1>
      <% end %>
    </div>

    <!-- load React header component instead -->
    <%#= javascript_pack_tag "credly_take_home_header" %>

    <%= yield %>
  </body>
</html>

app/views/recruit/index.html.erb
<%= link_to 'HOME', '/' %>
<body>

  <h1>Recruits</h1>
    <%= @recruits.map do |character| %>
      <% if character.certified == false %>
        <h3><%= link_to "Issue #{character.last_name} a badge?", "recruits/#{character.id}" %></h3>
        <h2><%= character.last_name %></h2>
        <p><%= image_tag(character.picture) %></p>
      <% else character.certified == true %>
        <h2><%= character.last_name %> is certified!</h2>
        <p><%= image_tag(character.picture) %></p>
      <% end %>
    <% end %>

</body>

app/views/recruit/show.html.erb
<h1>Recruit Show Page</h1>

<div class="effect2">
  <h3>Character: <%= @recruit.last_name %><br></h3>
  <%= image_tag(@recruit.picture) %>
</div>

app/views/static_pages/home.html.erb
<div>
<h1>Recruit Dashboard</h1>

<h3><%= link_to "Find Recruits", "/characters" %></h3>
<h3><%= link_to "Certify and View Recruits", "/recruits" %></h3>

<figure id="img-div">
  <img id="image"
     src="https://i.annihil.us/u/prod/marvel/images/OpenGraph-TW-1200x630.jpg"
</figure>
</div>